### ISSUE TITLE
Contribution proposal. 

### ISSUE THREAD

**Issue by Sharaf-Mansour** [kasuken/BlazorKit.Spinners#8]
## Request 
I would like to offer a little bit of help for your Repo.

#### 1. GitHub README.MD Formatting :-
It is safe to say that 
Having your code be displayed as this 
```Razor 
<div id="app">
  <div class="loaderWrapper">
    <span class="loaderMain"></span>
  </div>
</div>
```
Looks better than 
```
<div id="app">
  <div class="loaderWrapper">
    <span class="loaderMain"></span>
  </div>
</div>
```

## Closing 
Thank you for the great work and contribution for the dotnet community, I hope you accept my proposal and I will open PRs for each task.

**Comment by Sharaf-Mansour** [comment]
## I have this idea for the sample project ![image](https://user-images.githubusercontent.com/55330747/151380179-5f842e12-0eb1-4bb5-b654-a1deb1c9c544.png)

**Comment by kasuken** [comment]
Thanks for the feedback!
I will do that! :)

**Comment by Sharaf-Mansour** [comment]
I have made all those changes here [Sharaf-Mansour/BlazorKit.Spinners](https://github.com/Sharaf-Mansour/BlazorKit.Spinners)

- Dotnet 6 migration 
- Docs changes
- and the Select menu in the counter

**Comment by kasuken** [comment]
Send me a Pull Request! and thanks!

**Comment by Sharaf-Mansour** [comment]
@kasuken  Sorry for the delay had a lot of work, Here is the PR #9
